site_name: DoMB
repo_url: https://github.com/wisstock/DoMB_tools
repo_name: DoMB

theme:
  name: readthedocs

plugins:
- mkdocstrings:  # https://mkdocstrings.github.io/python/
    handlers:
      python:
        options:
          docstring_style: numpy
          docstring_section_style: spacy
          show_docstring_attributes: true
          merge_init_into_class: true
          show_signature: false
          show_if_no_docstring: false

nav:
    - Home: index.md
    - Registrations Types:
        - WF x2 m2: wf_x2_m2.md
    - Modules:
        - FRET: fret.md
        - Red-Green: rg.md
    - Utils: 
        - Masking: masking.md
        - Plotting: plotting.md
        - OIF File: oiffile.md

