[project]
name = "domb"
description = "DoMB tools: Python Toolkit of Department of Molecular Biophysics"

version = "2023.11-01"
authors = [{name = "Borys Olifirov", email = "omnia.fatum@gmail.com"}]

readme = "README.md"
license = {file = "LICENSE"}

requires-python = ">=3.9"

dependencies = [
    "autograd >= 1.6",
    "ipykernel >= 6.19",
    "jupyter >= 1.0",
    "matplotlib >= 3.7",
    "mkdocstrings[python] >= 0.18",
    "numpy >= 1.25",
    "opencv-python >= 4.5",
    "pandas >= 1.5",
    "pathos >= 0.3",
    "plotly >= 5.15",
    "scikit-image >= 0.19",
    "scikit-learn >= 1.0",
    "scikit-posthocs >= 0.7",
    "scipy >= 0.12"
]


[project.urls]
documentation = "https://domb.bio/"
Repository = "https://github.com/wisstock/DoMB_tools"


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
